version: '3'

services:
  web:
    build: .
    environment:
      - REDIS_HOST=redis
    container_name: prography
    command: poetry run python manage.py runserver 0:8000
    ports:
      - '8000:8000'
    volumes:
      - '.:/code/'
    platform: linux/amd64
