version: '3'

services:
  web:
    build: .
    environment:
      - REDIS_HOST=redis
    container_name: prography
    command: poetry run python manage.py runserver 0:8000
    ports:
      - '8000:8000'
    volumes:
      - '.:/code/'
    depends_on:
      - redis
    platform: linux/amd64
  redis:
    image: redis
    container_name: redis
    command: redis-server --port 6379
    platform: linux/amd64
    ports:
      - '6379:6379'
