name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3 # * checkout을 위한 토큰 설정부터, 저장소 복사까지 많은 일 수행
    - name: Set up Python
      uses: actions/setup-python@v4 # * github actions 으로 Python 사용하는 데 권장
    - run: |
        pip install --user poetry
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    # - name: Run Poetry
    #   uses: Gr1N/setup-poetry@v7
    #   with:
    #     poetry-version: "1.1.11"
    - name: Run Poetry install
      run: |
        poetry install
    - name: Run test
      run: |
        poetry run python manage.py test